version: '3'


tasks:
  up:
    desc: Creates the Azure PaaS infrastructure (App Service + Azure SQL)
    cmds:
    - task: init
    - task: apply

  init:
    desc: Initializes Terraform for the Azure PaaS deployment
    cmds:
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  apply:
    desc: Applies Terraform configuration for the Azure PaaS deployment
    cmds:
    - terraform apply -auto-approve -var "location={{.REGION}}" -compact-warnings
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  plan:
    desc: Shows Terraform execution plan for the Azure PaaS deployment
    cmds:
    - terraform plan -var "location={{.REGION}}" -compact-warnings
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  down:
    desc: Destroys the Azure PaaS resources and cleans up Terraform
    cmds:
    - az group delete -n {{.RG}} --yes --no-wait || true
    - powershell -Command "Remove-Item -Recurse -Force terraform.tfstate.d, .terraform.lock.hcl, .terraform, terraform.tfstate, terraform.tfstate.backup, .terraform.tfstate.lock.info -ErrorAction SilentlyContinue"
    vars:
      RG:
        sh: terraform output -raw resource_group_name
