version: '3'

tasks:
  up:
    desc: Creates the legacy infrastructure in Azure
    cmds:
    - task: init
    - task: apply

  init:
    desc: Initializes Terraform
    cmds:
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  apply:
    desc: Applies Terraform configuration
    cmds:
    - terraform apply -auto-approve -var "location={{.REGION}}" -compact-warnings
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  plan:
    desc: Shows Terraform execution plan
    cmds:
    - terraform plan -var "location={{.REGION}}" -compact-warnings
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  creds:
    desc: Shows SQL and VM credentials from Terraform output
    cmds:
    - cmd: echo "{{.CONNECT_STRING}} /w:1024 /h:768 [username:{{.USERNAME}} password:{{.PASSWORD}}]"
      silent: true
    - cmd: echo "SQL Password:{{.SQL_PASSWORD}}"
      silent: true      
    vars:
      USERNAME:
        sh: terraform output -raw vm_admin_username
      PASSWORD:
        sh: terraform output -raw vm_admin_password
      CONNECT_STRING:
        sh: terraform output -raw rdp_connection_string
      SQL_PASSWORD:
        sh: terraform output -raw sql_sa_password

  browse:
    desc: Opens the deployed website in the default browser
    cmds:
    - cmd: powershell -Command "Start-Process 'http://{{.IP}}'"
      silent: true
    vars:
      IP:
        sh: terraform output -raw vm_public_ip

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - az group delete -n {{.RG}} --yes --no-wait || true
    - powershell -Command "Remove-Item -Recurse -Force terraform.tfstate.d, .terraform.lock.hcl, .terraform, terraform.tfstate, terraform.tfstate.backup, .terraform.tfstate.lock.info -ErrorAction SilentlyContinue"
    vars:
      RG:
        sh: terraform output -raw resource_group_name
